export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY = 'GET_COUNTRY';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';

export const FUNCTIONS_LOADING = 'FUNCTIONS_LOADING';
export const GET_FUNCTIONS = 'GET_FUNCTIONS';
export const GET_FUNCTION = 'GET_FUNCTION';
export const ADD_FUNCTION = 'ADD_FUNCTION';
export const UPDATE_FUNCTION = 'UPDATE_FUNCTION';
export const DELETE_FUNCTION = 'DELETE_FUNCTION';

